apiVersion: v1
kind: Service
metadata:
  name: aks-github-actions-demo-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: aks-github-actions-demo
